server:
  port: 80
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password: root123
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 234222501342-q938t6sshsnut5k7prrgan8e60c8qgjn.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          
          